name: Qodana

on:
  workflow_dispatch:
  # TODO(ChrisCarini) - Do not run this on a schedule; this is a fork. Please don't use all my GHA (free) minutes :)
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
